services:
  db: 
    image: postgres:16
    container_name: db
    env_file:
      - ./be/.env
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres} 
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_PORT=${DB_PORT:-5432}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./be
    container_name: backend
    env_file:
      - .env
    ports:
      - "${BE_PORT}:8000"
    depends_on:
      - db
  frontend:
    build: ./fe
    container_name: frontend
    env_file:
      - .env
      - ./fe/.env
    ports:
      - "${FE_PORT}:5173"
    depends_on:
      - backend
      - db
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #   - ./nginx.conf:/etc/nginx/conf.d/app.conf 
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  postgres_data: 